### PR TITLE
Add ja Translation

### PR DESCRIPTION
**Pull request by shg166**
It was on Github, so I translated it anyway.
Is this a mod that ignores the IPT or TLM spawn time and controls it with this mod?
Or is it a mod that controls the spawn time on the depot side regardless of the mod and route?

### CODE REVIEW

**Comment by algernon-A** [comment]
Controls the spawn time of the depot regardless of route.  Works with IPT and TLM - spawning delay will be whichever has the longest delay sit (this mod or IPT/TLM), or can be used on its own, too.

**Comment by shg166** [comment]
Thanks for the reply.
That's a feature I'd like to use with airship and passenger helicopter depots.
These two can get clogged up very quickly by the way the routes are connected from the depot.
I would like to make the spawn time longer than the IPT or TLM spawn time.

**Comment by algernon-A** [comment]
Sure - I'll add those two to the list; I'm about to release the current state as 1.0, and will look at those for the next update.

**Comment by shg166** [comment]
Thank you very much for all the information.
I am waiting for the release of the mod.

**Comment by algernon-A** [comment]
Hi, there's been another translation string added for 1.1:
`<Translation ID="VSD_DEP_PER" String="Use separate timers for each depot" />`

(airship/helicopters are planned for 1.2)

**Pull request merged**
